### ISSUE TITLE
Add upstream PostgreSQL APT key - FAILED

### ISSUE THREAD

**Issue by mcmegavolt** [debops/ansible-rails_deploy#26]
I'm getting this while running playbook, what am I doing wrong?

```
TASK [debops.postgresql : Add upstream PostgreSQL APT key] ******************************************************************************************************
fatal: [185.67.2.117]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname == rails_deploy_hosts_master and (rails_deploy_dependencies is defined and 'database' in rails_deploy_dependencies) and rails_deploy_database_adapter == 'postgresql'' failed. The error was: error while evaluating conditional (inventory_hostname == rails_deploy_hosts_master and (rails_deploy_dependencies is defined and 'database' in rails_deploy_dependencies) and rails_deploy_database_adapter == 'postgresql'): {{ groups[rails_deploy_hosts_group][0] }}: 'dict object' has no attribute u'debops_rails_deploy'\n\nThe error appears to have been in '/home/ap/.ansible/roles/debops.postgresql/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add upstream PostgreSQL APT key\n  ^ here\n"}
```

**Comment by drybjed** [comment]
It looks like you don't have the `debops_rails_deploy` Ansible inventory group defined, which this role depends on. Can you add it and see if that helps?

**Comment by mcmegavolt** [comment]
Please, look at my [repository](https://github.com/mcmegavolt/ansible_deploy) I have just created (secret data was replaced)

**Command is:** `ansible-playbook playbook.yml -i hosts`

I'm still getting the same error. What is wrong with that?

**Comment by drybjed** [comment]
You need to add another section in the inventory file:
```
[debops_rails_deploy]
3.2.4.1
```
Then, Ansible will have this group defined and role should proceed.

However, the role has not been updated in some time, and don't expect that all the roles it uses as dependencies will work as expected.

**Comment by mcmegavolt** [comment]
Oh, that helped ) 
But Now I have another issue, configs looks strange or it is normal?

```
TASK [debops.nginx : Assert that no legacy options are used] ****************************************************************************************************
ok: [185.67.2.117 -> localhost] => (item={u'welcome_domain': u'67.2.117.hostpro.com.ua', u'name': [u'welcome'], u'csp_enabled': True, u'welcome': True, u'enabled': True, u'csp': u"default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self';"}) => {
    "changed": false, 
    "failed": false, 
    "item": {
        "csp": "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self';", 
        "csp_enabled": true, 
        "enabled": true, 
        "name": [
            "welcome"
        ], 
        "welcome": true, 
        "welcome_domain": "67.2.117.hostpro.com.ua"
    }, 
    "msg": "All assertions passed"
}
ok: [185.67.2.117 -> localhost] => (item={u'name': [u'localhost', u'127.0.0.1', u'[::1]'], u'acme': False, u'welcome': True, u'enabled': True, u'ssl': False, u'welcome_css': False}) => {
    "changed": false, 
    "failed": false, 
    "item": {
        "acme": false, 
        "enabled": true, 
        "name": [
            "localhost", 
            "127.0.0.1", 
            "[::1]"
        ], 
        "ssl": false, 
        "welcome": true, 
        "welcome_css": false
    }, 
    "msg": "All assertions passed"
}
ok: [185.67.2.117 -> localhost] => (item={u'root': u'/srv/www/sites/acme/public', u'filename': u'acme-challenge', u'enabled': False, u'name': [u'acme.67.2.117.hostpro.com.ua'], u'delete': True}) => {
    "changed": false, 
    "failed": false, 
    "item": {
        "delete": true, 
        "enabled": false, 
        "filename": "acme-challenge", 
        "name": [
            "acme.67.2.117.hostpro.com.ua"
        ], 
        "root": "/srv/www/sites/acme/public"
    }, 
    "msg": "All assertions passed"
}
ok: [185.67.2.117 -> localhost] => (item={u'name': [u'185.67.2.117.hostpro.com.ua'], u'error_pages': {u'404': u'/404.html', u'422': u'/422.html', u'500': u'/500.html', u'502 503 504': u'/502.html'}, u'enabled': True, u'default': False, u'root': u'/var/local//185.67.2.117.hostpro.com.ua//src/public', u'location_list': [{u'pattern': u'/', u'options': u'try_files $uri $uri/index.html $uri.html @;\n'}, {u'pattern': u'~ ^/(assets|system)/', u'options': u'gzip_static on;\nexpires max;\nadd_header Cache-Control public;\nadd_header Last-Modified "";\nadd_header ETag "";\n'}, {u'pattern': u'@', u'options': u'gzip off;\nproxy_set_header   X-Forwarded-Proto $scheme;\nproxy_set_header   Host              $http_host;\nproxy_set_header   X-Real-IP         $remote_addr;\nproxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\nproxy_redirect     off;\nproxy_pass         http://;\n'}]}) => {
    "changed": false, 
    "failed": false, 
    "item": {
        "default": false, 
        "enabled": true, 
        "error_pages": {
            "404": "/404.html", 
            "422": "/422.html", 
            "500": "/500.html", 
            "502 503 504": "/502.html"
        }, 
        "location_list": [
            {
                "options": "try_files $uri $uri/index.html $uri.html @;\n", 
                "pattern": "/"
            }, 
            {
                "options": "gzip_static on;\nexpires max;\nadd_header Cache-Control public;\nadd_header Last-Modified \"\";\nadd_header ETag \"\";\n", 
                "pattern": "~ ^/(assets|system)/"
            }, 
            {
                "options": "gzip off;\nproxy_set_header   X-Forwarded-Proto $scheme;\nproxy_set_header   Host              $http_host;\nproxy_set_header   X-Real-IP         $remote_addr;\nproxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\nproxy_redirect     off;\nproxy_pass         http://;\n", 
                "pattern": "@"
            }
        ], 
        "name": [
            "185.67.2.117.hostpro.com.ua"
        ], 
        "root": "/var/local//185.67.2.117.hostpro.com.ua//src/public"
    }, 
    "msg": "All assertions passed"
}

TASK [debops.nginx : DebOps pre_tasks hook] *********************************************************************************************************************
fatal: [185.67.2.117]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}
```

**Comment by drybjed** [comment]
The `debops.nginx` role uses a custom lookup plugin included in DebOps, `task_src`, and Ansible wasn't able to find it. You can [download it](https://github.com/debops/debops/blob/master/ansible/playbooks/lookup_plugins/task_src.py) and put it in `lookup_plugins/` directory somewhere where Ansible is looking for them (check the configuration). You will also need to install the `debops` package from PyPI, it contains some additional functions the plugin is using.

**Comment by mcmegavolt** [comment]
So, it helped! ansible.cfg can be placed in working directory with content:
```
[defaults]
lookup_plugins = ~/.ansible/plugins/lookup_plugins/
```

Now there is another issue ((
```
TASK [debops.nginx : Create default welcome page if enabled] ****************************************************************************************************
 [WARNING]: Unable to find 'lookup/ferm__fix_dependent_rules.j2' in expected paths.

failed: [185.67.2.117] (item={u'welcome_domain': u'67.2.117.hostpro.com.ua', u'name': [u'welcome'], u'csp_enabled': True, u'welcome': True, u'enabled': True, u'csp': u"default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self';"}) => {"changed": false, "failed": true, "item": {"csp": "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self';", "csp_enabled": true, "enabled": true, "name": ["welcome"], "welcome": true, "welcome_domain": "67.2.117.hostpro.com.ua"}, "msg": "AnsibleError: {{ lookup(\"template\", \"lookup/ferm__fix_dependent_rules.j2\", convert_data=False) | from_json }}: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: the template file lookup/ferm__fix_dependent_rules.j2 could not be found for the lookup"}
ok: [185.67.2.117] => (item={u'name': [u'localhost', u'127.0.0.1', u'[::1]'], u'acme': False, u'welcome': True, u'enabled': True, u'ssl': False, u'welcome_css': False})
skipping: [185.67.2.117] => (item={u'root': u'/srv/www/sites/acme/public', u'filename': u'acme-challenge', u'enabled': False, u'name': [u'acme.67.2.117.hostpro.com.ua'], u'delete': True}) 
skipping: [185.67.2.117] => (item={u'name': [u'185.67.2.117.hostpro.com.ua'], u'error_pages': {u'404': u'/404.html', u'422': u'/422.html', u'500': u'/500.html', u'502 503 504': u'/502.html'}, u'enabled': True, u'default': False, u'root': u'/var/local//185.67.2.117.hostpro.com.ua//src/public', u'location_list': [{u'pattern': u'/', u'options': u'try_files $uri $uri/index.html $uri.html @;\n'}, {u'pattern': u'~ ^/(assets|system)/', u'options': u'gzip_static on;\nexpires max;\nadd_header Cache-Control public;\nadd_header Last-Modified "";\nadd_header ETag "";\n'}, {u'pattern': u'@', u'options': u'gzip off;\nproxy_set_header   X-Forwarded-Proto $scheme;\nproxy_set_header   Host              $http_host;\nproxy_set_header   X-Real-IP         $remote_addr;\nproxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\nproxy_redirect     off;\nproxy_pass         http://;\n'}]})
```

**Comment by drybjed** [comment]
This is an issue with Ansible and jinja2. You need to install jinja2 2.8 to have it work correctly.

**Comment by mcmegavolt** [comment]
Thats ok, moving further ))) Issues.... (((

```
TASK [debops.nginx : DebOps pre_tasks hook] *********************************************************************************************************************
task path: /home/ap/.ansible/roles/debops.nginx/tasks/main.yml:20
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 456, in _execute
    include_file = templar.template(include_file)
  File "/usr/local/lib/python3.5/dist-packages/ansible/template/__init__.py", line 450, in template
    disable_lookups=disable_lookups,
  File "/usr/local/lib/python3.5/dist-packages/ansible/template/__init__.py", line 672, in do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 196, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ansible/template/__init__.py", line 579, in _lookup
    instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/loader.py", line 363, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/loader.py", line 339, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ap/.ansible/plugins/lookup_plugins/task_src.py", line 23, in <module>
    from debops import *
  File "/usr/local/lib/python3.5/dist-packages/debops/__init__.py", line 32, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

fatal: [185.67.2.117]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by drybjed** [comment]
Hmm, no `ConfigParser` module? What do you use as an Ansible Controller, Linux, MacOS? Are you using Python in a virtualenv which might be not complete?

**Comment by mcmegavolt** [comment]
I've just removed virtualenv package and getting the same error, what additional info do you need?
Ubuntu 16.04
I'm confusing when see two versions of python, is it okay?
```
python --version
Python 2.7.12
python3 --version
Python 3.5.2
```

**Comment by drybjed** [comment]
Sure, python 2 and python 3 are separate.

I think that you installed `debops` package in a Python 3 `virtualenv` environment, since [Python 3 doesnot have `ConfigParser` module](https://stackoverflow.com/a/14087705/6996970). The `debops` Python package does not support Python 3 at the moment. Try installing Ansible and DebOps in a Python 2 `virtualenv` environment.

**Comment by mcmegavolt** [comment]
So, I have reinstalled my Ubuntu 16.05 system with Python2.7 (no virtualenv).

Now I have this error:

```
TASK [debops.rails_deploy : Install app packages] *********************************************************************************************
failed: [185.67.2.117] (item=[u"rails_deploy_packages + [ 'git' ]"]) => {"changed": false, "failed": true, "item": ["rails_deploy_packages + [ 'git' ]"], "msg": "No package(s) matching 'rails_deploy_packages + [ 'git' ]' available"}
```

**Comment by drybjed** [comment]
It seems that after a reinstall the APT cache is not up to date. Run `apt-get update` and try running Ansible again.

**Comment by mcmegavolt** [comment]
Sorry, it did not help ((

**Comment by drybjed** [comment]
Well, then, what happens when you try installing the `git` package manually?

**Comment by mcmegavolt** [comment]
**On the VPS server:**
```
$ sudo apt-get install git
[sudo] password for cfac: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1.3).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

**Comment by drybjed** [comment]
Ahh, I know what's up, my bad. The `rails_deploy_packages` is interpreted as a string, you would need to change it to `{{ rails_deploy_packages }}` so that it can be templated by Jinja to the actual list of packages.

Did I tell you that this role hasn't been updated in a while?

**Comment by mcmegavolt** [comment]
Yes, you did ))

Where I should change it, I can make a PR.

**Comment by drybjed** [comment]
If you want to help update this role, I would do it like this:

- start with forking the [`debops/debops`](https://github.com/debops/debops/) repository. You can simlink the `debops.rails_deploy` role from there to where it currently sits in your filesystem.
- make a branch and start fixing the role as you go.
- when the new role is ready, clean up your commits and post a PR to the DebOps monorepo.

As to where, use the friendly `grep` command, it probably will be different variables in different places.

**Comment by mcmegavolt** [comment]
Okay, I'm on it.

Help to fix this, please:
```
TASK [debops.rails_deploy : Create PostgreSQL user] ***************************************************************************************
fatal: [185.67.2.117]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: unknown user: postgres\nsudo: unable to initialize policy plugin\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by drybjed** [comment]
Looks like you forked **this** repository and not `debops/debops`, just a heads up.

The `debops.postgresql` role that is used by the `rails_deploy` role to manage the database is a "client-side" role. You also want to use the `debops.postgresql_server` role against that host to prepare it to be a PostgreSQL server. But don't include it in the dependencies of the `rails_deploy` role, that way the PostgreSQL server can be either local or on a remote host - the `debops.postgresql` role takes care to manage both the same for the roles that use it.

I suspect that you want to use the `debops.rails_deploy` as a standalone and not the entire DebOps "stack" of roles. Unfortunately this will probably quickly get out of hand, since some roles depend on others, like `debops.ferm`, debops.apt_preferences`, etc. The dependencies are defined through the playbooks, so it's possible to not have them, but you will need to take care of the things like firewall by yourself in that case.

**Comment by mcmegavolt** [comment]
I have used **postgresql_server** role first to prepare db and it passed.

Now I have this problem while playing *rails_deploy* role:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Tfhtd7/ansible_module_postgresql_user.py", line 779, in main
    db_connection = psycopg2.connect(**kw)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not translate host name "185.67.2.117.hostpro.com.ua" to address: Name or service not known
```

**Comment by drybjed** [comment]
Looks like `185.67.2.117.hostpro.com.ua` FQDN does not exist in the DNS. I suppose that you could try and add it in `/etc/hosts`, perhaps that would help.

NB, the traceback like that might not be helpful all the time, remember to include the full task error, with the task name as well. That way I know the code to look for.

**Comment by mcmegavolt** [comment]
I have added to **/etc/hosts**:
`127.0.0.1 185.67.2.117.hostpro.com.ua`

replayed **postgresql_server* role and tried again:
```
TASK [mcmegavolt.rails_deploy : Create PostgreSQL user] ***************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationalError: FATAL:  pg_hba.conf rejects connection for host "127.0.0.1", user "postgres", database "postgres", SSL off
```

**Comment by drybjed** [comment]
I suppose that this is an issue with the `postgresql_user` task in the `debops.rails_deploy` role. You can look at how the `postgresql_user` tasks look in the `debops.postgresql` role and update the former to use the same format.
